spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leave_application?createDatabaseIfNotExist=true
    username: root
    password: Monu@281611
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update